name: impact_sc
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.9
  - pip
  
  # Core scientific stack
  - numpy>=1.21
  - pandas>=1.3
  - scipy>=1.7
  - scikit-learn>=1.0
  - matplotlib>=3.5
  - seaborn>=0.11
  
  # Single-cell analysis
  - scanpy>=1.9
  - anndata>=0.8
  - leidenalg>=0.8
  - louvain>=0.7
  
  # Specialized packages - Apple Silicon compatible versions
  - pytorch::pytorch>=1.11
  - pytorch::torchvision>=0.12
  - pytorch::torchaudio>=0.11
  - transformers>=4.18
  - pytorch-lightning>=1.6
  
  # Development tools
  - jupyter
  - ipython
  - black
  - flake8
  
  # Pip-only packages
  - pip:
    - cell2sentence>=0.1
    - decoupler>=1.3
    - gseapy>=1.0 